repos:
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
-   repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
    - id: black
- repo: https://github.com/PyCQA/flake8
  rev: 5.0.3
  hooks:
  - id: flake8

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: debug-statements

-   repo: https://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
    - id: shell-lint
