name: Newsfragments

on:
  pull_request:
    branches-ignore:
      - 'dials-?.*'

jobs:
  rename-news:
    name: Newsfragment Checks
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Check newsfragment
        run: |
          set -x
          if [[ -n "$(ls newsfragments/XXX.*)" ]]; then
            git config user.name "${GITHUB_ACTOR}"
            git config user.email "noreply@dials.github.io"
            for fragment in newsfragments/XXX.*; do
              target_file="$(echo "${fragment}" | sed "s/XXX/${{github.event.number}}/")"
              git mv $fragment $target_file
              git add $target_file
            done
            git commit -m "Rename XXX.* newsfragments to PR number"
            git push origin ${GITHUB_REF}
          fi
