name: Newsfragments

on:
  pull_request:
    branches-ignore:
      - 'dials-?.*'

jobs:
  rename-news:
    name: Newsfragment Checks
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Check newsfragment
        run: |
          # set -x
          if [[ -n "$(ls newsfragments/XXX.*)" ]]; then
            git config user.name "${GITHUB_ACTOR}"
            git config user.email "noreply@dials.github.io"
            HEAD_REPO="${{github.event.pull_request.head.repo.full_name}}"
            HEAD_BRANCH="${{ github.event.pull_request.head.ref }}"
            git remote add fork https://x-access-token:${GITHUB_TOKEN}@github.com/$HEAD_REPO.git
            git fetch fork
            echo "Local log"
            git log --oneline --graph --decorate fork/${HEAD_BRANCH}..47a38a1 HEAD..47a38a1
            # Rewind this to the head of the PR instead of the post-PR merge point
            git checkout -b _rename_news fork/${HEAD_BRANCH}

            for fragment in newsfragments/XXX.*; do
              target_file="$(echo "${fragment}" | sed "s/XXX/${{github.event.number}}/")"
              git mv $fragment $target_file
              git add $target_file
            done
            git commit -m "Rename XXX.* newsfragments to PR number"

            echo "Event path"
            cat "$GITHUB_EVENT_PATH"
            echo "Push"
            git push fork HEAD:"${HEAD_BRANCH}"
          fi
